CREATE TABLE
  product_.lao_crns (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    crn TEXT,
    version INTEGER,
    last_updated TIMESTAMP
  );

CREATE TABLE
  product_.lao_exclusions (
    crn_user_id TEXT PRIMARY KEY,
    crn TEXT,
    user_id TEXT,
    reason TEXT,
    since TIMESTAMPTZ,
    until TIMESTAMPTZ
  );

CREATE TABLE
  product_.lao_restrictions (
    crn_user_id TEXT PRIMARY KEY,
    crn TEXT,
    user_id TEXT,
    reason TEXT,
    since TIMESTAMPTZ,
    until TIMESTAMPTZ
  );