version: 2.1

orbs:
  reporting: ministryofjustice/hmpps-reporting@dev:b483ed19ea27e34be55ded51ec9606ac4355ddf3
  
workflows:
  checkout-build-publish:
    jobs:               
      - reporting/aws_invoke_lambda:
          function: dpr-test-flyway-function
          is_mock: false
          ref: << pipeline.git.branch >><< pipeline.git.tag >>
          filters:
            branches:
              only: /.*/
            tags:
              ignore: /.*/
          context:
            - hmpps-reporting-common
            - hmpps-reporting-orb