version: 2.1

orbs:
  reporting: ministryofjustice/hmpps-reporting@dev:61958f6d113d8758149602e41da4e496a539f56e
  
workflows:
  checkout-build-publish:
    jobs:               
      - reporting/aws_invoke_lambda:
          function: dpr-test-flyway-function
          is_mock: false
          ref: << pipeline.git.branch >><< pipeline.git.tag >>
          filters:
            branches:
              only: /.*/
            tags:
              ignore: /.*/
          context:
            - hmpps-reporting-common
            - hmpps-reporting-orb