version: 2.1

orbs:
  reporting: ministryofjustice/hmpps-reporting@dev:5a87bdb48cf4bdf90b54266f2b5b9130e56a6f89
  slack: circleci/slack@4.12.5

parameters:
  function:
    type: string
    default: "dpr-transfer-component-function"
  notify_slack:
    type: boolean
    default: true
    description: Send notifications to Slack
  notify_jira:
    type: boolean
    default: true
    description: Send notifications to Associated Jira
  test_ready:
    type: boolean
    default: true
    description: Deploy to Test Environment
  preprod_ready:
    type: boolean
    default: false
    description: Deploy to PreProd Environment, OBSOLETE

workflows:
  checkout-build-publish:
    jobs:               
      - reporting/aws_invoke_lambda:
          function: << pipeline.parameters.function >>
          is_mock: false
          test_ready: << pipeline.parameters.test_ready >>
          preprod_ready: << pipeline.parameters.preprod_ready >>          
          ref: << pipeline.git.branch >><< pipeline.git.tag >>
          notify_slack: << pipeline.parameters.notify_slack >>
          filters:
            branches:
              only: /.*/
            tags:
              ignore: /.*/
          context:
            - hmpps-reporting-common
            - hmpps-reporting-orb
