version: 2.1

orbs:
  reporting: ministryofjustice/hmpps-reporting@dev:430d6f282f8ac526311288c3019042e0b781244a
  
workflows:
  checkout-build-publish:
    jobs:               
      - reporting/aws_invoke_lambda:
          function: dpr-transfer-component-function
          is_mock: false
          ref: << pipeline.git.branch >><< pipeline.git.tag >>
          filters:
            branches:
              only: /.*/
            tags:
              ignore: /.*/
          context:
            - hmpps-reporting-common
            - hmpps-reporting-orb