version: 2.1

orbs:
  reporting: ministryofjustice/hmpps-reporting@dev:0eaa25571bac6eba58d5bb67661178478eef00ea
  
workflows:
  checkout-build-publish:
    jobs:               
      - reporting/aws_invoke_lambda:
          function: dpr-test-flyway-function
          is_mock: false
          ref: << pipeline.git.branch >><< pipeline.git.tag >>
          filters:
            branches:
              only: /.*/
            tags:
              ignore: /.*/
          context:
            - hmpps-reporting-common
            - hmpps-reporting-orb